#!/bin/sh

venv/bin/python reformulate.py --dataset flickr30k --input_file blip_flickr_style_test_captions.json --output_file blip_flickr_style_test_captions_reformulated.json --model_path /cs/labs/oabend/uriber/blip_reformulation_output/checkpoint_02.pth
