image_root: '/cs/labs/oabend/uriber/datasets/COCO'
ann_root: 'annotation'
coco_gt_root: 'annotation/coco_gt'
local_ann_file: 'reformulation_data/batch_5/batch_5_reformulation_data.json'
#local_ann_file: 'pascal_data/pascal_orig.json'

# set pretrained as a file path or an url
pretrained: 'output/after_batch_5_gt_clip/checkpoint_best.pth'

# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 16
init_lr: 1e-5

# vit: 'large'
# vit_grad_ckpt: True
# vit_ckpt_layer: 5
# batch_size: 16
# init_lr: 2e-6

image_size: 384

# generation configs
max_length: 20  
min_length: 5
num_beams: 3
prompt: 'a picture of '

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 1

